[workspace]
members = [
    "crates/reactor-protocol",
    "crates/reactor-core",
    "crates/reactor-ffi",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/reactor-team/reactor-client-sdks"

[workspace.dependencies]
reactor-protocol = { path = "crates/reactor-protocol" }
reactor-core     = { path = "crates/reactor-core" }
reactor-webrtc   = "0.7"

serde       = { version = "1",   features = ["derive"] }
serde_json  = "1"
thiserror   = "2"
async-trait = "0.1"
futures     = "0.3"
log         = "0.4"
env_logger  = { version = "0.11", default-features = false, features = ["auto-color"] }
mime_guess  = "2"
tokio       = { version = "1", features = ["full"] }
