//! Rust bindings for the `reactor_wire` protobuf schema owned by
//! `reactor-runtime`, generated by `build.rs` from the `.proto` sources it
//! fetches at build time from the pinned `reactor-runtime` release (see
//! `proto/WIRE_VERSION`). Nothing is vendored into this repo.

pub mod struct_convert;
pub mod v1;
