//! Rust bindings for the `reactor_wire` protobuf schema owned by
//! `reactor-runtime`, generated by `build.rs` from the vendored `.proto`
//! sources in `proto/reactor_wire/v1/*.proto` (see `proto/WIRE_VERSION` for
//! the pinned release).

pub mod struct_convert;
pub mod v1;
